[package]
name = "initial_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delta_e = "0.2.1"
image = "0.24.7"
